version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build: .
    command: go run main.go
    volumes:
      - .:/go/src/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - IP_RATE_LIMIT=5
      - TOKEN_RATE_LIMIT=10
      - BLOCK_DURATION=60
    depends_on:
      - redis
    ports:
      - "8080:8080"
